apiVersion: batch/v1
kind: Job
metadata: 
  name: mouse-model-${NUM}-lr-no-decay
spec:
  backoffLimit: 5
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: mouse-model-${NUM}-lr-no-decay
    spec:
      restartPolicy: Never
      containers:
      - name: mouse-model-${NUM}-lr-no-decay
        image: jmlehrer/sims:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: [
          "wandb login --relogin $(cat wandbcreds) &&\
          python model_zoo/mouse_model.py --test"
          # "python models/mouse_model.py \
          # --lr=${LR} \
          # --weight-decay=0 \
          # --name=mouse-model-${NUM}-lr-no-decay"
        ]
        resources:
          limits:
            memory: 256Gi
            cpu: "32"
            nvidia.com/gpu: "1"
          requests:
            memory: 64Gi
            cpu: "32"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
        # SystemV shared memory
        - name: "dshm"
          mountPath: "/dev/shm"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
